-- Phase 4: Agent préparation — opportunity_preps table + prep agent_run_type

-- Add 'prep' to agent_run_type enum
do $$
begin
  alter type public.agent_run_type add value if not exists 'prep';
exception when others then null;
end $$;

-- opportunity_preps: append-only preparation plan history per opportunity and user
create table if not exists public.opportunity_preps (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id),
  agent_run_id uuid not null unique references public.agent_runs(id),
  user_id uuid not null references auth.users(id),
  is_backfilled boolean not null default false,
  is_current boolean not null default false,
  prep_version text not null,
  model text null,
  generation_ms integer null,
  checklist jsonb not null default '[]'::jsonb,
  missing_docs text[] not null default '{}',
  effort_days numeric null,
  blockers text[] not null default '{}',
  response_plan text not null,
  input_snapshot jsonb null,
  created_at timestamptz not null default now()
);

create unique index if not exists opportunity_preps_one_current_per_user_opportunity_idx
  on public.opportunity_preps (opportunity_id, user_id)
  where is_current = true;

create index if not exists opportunity_preps_user_current_created_at_idx
  on public.opportunity_preps (user_id, is_current, created_at desc);

create index if not exists opportunity_preps_opportunity_user_created_at_idx
  on public.opportunity_preps (opportunity_id, user_id, created_at desc);

alter table public.opportunity_preps enable row level security;

drop policy if exists "Users read own preps" on public.opportunity_preps;
create policy "Users read own preps"
  on public.opportunity_preps
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Service role manages preps" on public.opportunity_preps;
create policy "Service role manages preps"
  on public.opportunity_preps
  for all
  to service_role
  using (true)
  with check (true);

revoke all on table public.opportunity_preps from public;
revoke all on table public.opportunity_preps from anon;
revoke insert, update, delete on table public.opportunity_preps from authenticated;
grant select on table public.opportunity_preps to authenticated;
grant all on table public.opportunity_preps to service_role;

comment on table public.opportunity_preps is 'Append-only preparation plan history per opportunity and user.';
comment on column public.opportunity_preps.id is 'Primary key for the prep row.';
comment on column public.opportunity_preps.opportunity_id is 'Canonical opportunity for this plan.';
comment on column public.opportunity_preps.agent_run_id is 'Run ledger row that produced this plan.';
comment on column public.opportunity_preps.user_id is 'User subject for the plan.';
comment on column public.opportunity_preps.is_current is 'Marks the current prep row for an opportunity and user.';
comment on column public.opportunity_preps.prep_version is 'Prep logic/version identifier.';
comment on column public.opportunity_preps.checklist is 'Array of {task, priority} objects generated by the agent.';
comment on column public.opportunity_preps.missing_docs is 'Documents required but not yet in opportunity_documents.';
comment on column public.opportunity_preps.effort_days is 'Estimated working days to prepare a full response.';
comment on column public.opportunity_preps.blockers is 'Main potential blockers for this opportunity.';
comment on column public.opportunity_preps.response_plan is 'Strategic approach for responding to this opportunity.';
